version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"  # Set both to half of the memory you allocated to Colima
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  neo4j:
    image: neo4j:5.22.0
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - neo4j
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j

volumes:
  esdata:
  neo4jdata: